### ISSUE TITLE
How do you make this run independent of glibc installed in the host?

### ISSUE THREAD

**Issue by brunoais** [mmtrt/WINE_AppImage#10]
I've been trying to do the same kind of packaging and I'm having issues with libc versions where wine is using libc of the host instead of libc of the AppImage. I can't seem to find how you solved it here. Any hints?

I'm not sure if your AppImage would work on a system regardless of their installed linux OK, though...

The other one I found before is here: https://github.com/Hackerl/Wine_Appimage/

**Comment by mmtrt** [comment]
Well I'm using [this](https://github.com/AppImageCrafters/appimage-builder) to build wine appaimge which has methods to handle libc calls and I'm using wine build example recipe from it with some changes not related to libc in recipe.

**Comment by brunoais** [comment]
OK. Thank you!
