### ISSUE TITLE
(Question) Building native on local OS

### ISSUE THREAD

**Issue by alphafox02** [mmtrt/WINE_AppImage#13]
Would building the appimage native on a local 20.04 install in any way cut down the size of the appaimge by using existing installed libraries vs additional ones inside the appaimge? I’ve been thinking of including a wine appimage inside DragonOS (based on 20.04) but I’m limited on remaining space I have to play with and still make a distributable ISO.

**Comment by mmtrt** [comment]
I've updated repo now appimages have shade quite MBs though you can further cut down size by skipping bundle apt pkgs only keep bash, dash and manually add wine deb pkgs into AppDir.

**Comment by alphafox02** [comment]
Awesome I will check again. The stable 7.0 app image was running all these applications last night. 
![C3D782A7-BF78-423E-8915-33718988E0C8](https://user-images.githubusercontent.com/44436101/183289281-5106ba6c-eb6f-4583-8739-ef21a282cac3.jpeg)

**Comment by alphafox02** [comment]
Thank you for reduced size, I’ll also try the other things you mentioned.
