### ISSUE TITLE
Include a build with gecko/mono embedded

### ISSUE THREAD

**Issue by ruanformigoni** [mmtrt/WINE_AppImage#14]
Hi,

Would it be possible to pre-package `wine-mono` and `wine-gecko` with another release file?

Thanks!

**Comment by mmtrt** [comment]
This increases appimage size so thats why I've excluded it.

**Comment by suisuyy** [comment]
> 

never mind size , it is already very large : ),i want them included

**Comment by mmtrt** [comment]
I've added wine mono & gecko so test this thank you.

**Comment by suisuyy** [comment]
> I've added wine mono & gecko so test this thank you.

oh thanks,really nice job
