### ISSUE TITLE
where is winege

### ISSUE THREAD

**Issue by suisuyy** [mmtrt/WINE_AppImage#17]
thanks make this appimage,i found winege-lol,but there is no winege

**Comment by mmtrt** [comment]
It didn't worked during testing so I removed it.

**Comment by ruanformigoni** [comment]
I got it working in my [fork](https://github.com/ruanformigoni/wine/releases).

**Comment by ruanformigoni** [comment]
Hi @mmtrt , I've tested it and it was crashing for me too in some applications. However I made it work with the appimage-builder docker container. The solution for me was to use a downgraded version of appimage-builder, [this one](https://github.com/AppImageCrafters/appimage-builder/releases/download/v0.9.1/appimage-builder-0.9.1-fb653e5-x86_64.AppImage).

Edit: Nvm, I have no idea.

**Comment by mmtrt** [comment]
appimage-builder issue can't be fixed here.

**Comment by mmtrt** [comment]
It should be working now.
