### ISSUE TITLE
[Feature Request] Possible to include dxvk and vkd3d?

### ISSUE THREAD

**Issue by xiujk71** [mmtrt/WINE_AppImage#18]
Some games requires dxvk or vkd3d to work. Was wondering if it is possible to include them in the appimage version of wine? 😁

**Comment by mmtrt** [comment]
you can install it easily with winetricks as appimage ships winetricks with it.

with this command.

`./wine.appimage winetricks dxvk191`

**Comment by xiujk71** [comment]
Ahh, apologies, didn't know dxvk was available in winetricks, have been relying on lutris too much 😅

I just tried the winetricks command earlier, and it worked perfect. Thanks for the help :DD
