### ISSUE TITLE
It seems software that uses openal32.dll can't work in Wine Appimage

### ISSUE THREAD

**Issue by user1-github** [mmtrt/WINE_AppImage#20]
When I try to launch software that uses openal32.dll I get the error:
err:module:import_dll Loading library OpenAL32.dll
I've read that Wine needs the native Linux openal package in order for software that uses openal to work in Wine.
So my question is: Can the Linux openal package be shipped with the appimage?

Also, does anyone know if this situation will change or remain the same when Wine will finish the PE conversion?

**Comment by ruanformigoni** [comment]
I've had a similar issue, can't remember if it was openal. Could you test with [wine-ge](https://github.com/ruanformigoni/wine/releases)? It comes with some patches that may help.

**Comment by user1-github** [comment]
@ruanformigoni I think I tried one of these Appimages, but they don't work on my distro (Fedora Silverblue, which is an immutable distro) because they don't ship 32 bit Mesa drivers. I mean I would happily test that, but I can't because of my current distro.

**Comment by ruanformigoni** [comment]
I see,

Does it work if you install [openal](https://src.fedoraproject.org/rpms/openal-soft) systemwide? I can try to make a build with it included.

**Comment by mmtrt** [comment]
@user1-github test again.

**Comment by user1-github** [comment]
@mmtrt It works now with the new build, thanks!

**Comment by mmtrt** [comment]
good.
