### ISSUE TITLE
I test your build appimage for wine in i3wm environment is slot

### ISSUE THREAD

**Issue by newyorkthink** [mmtrt/WINE_AppImage#22]
in xfce or i3wm , you wine appimage not run any softw~

**Comment by mmtrt** [comment]
anylog or error?

**Comment by mmtrt** [comment]
info about your os.

**Comment by newyorkthink** [comment]
my os info
![image](https://user-images.githubusercontent.com/87791643/213185227-0a55be77-1dae-4d15-85ad-acb56f660121.png)

**Comment by mmtrt** [comment]
which app you are trying not working?

**Comment by newyorkthink** [comment]
the first run wine
![image](https://user-images.githubusercontent.com/87791643/213185413-803a8379-33e6-4171-a7c8-ddfa8f34bea8.png)

when i run wine have causing the system to freeze

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/213185709-7ba7610c-761f-4bfd-a7e2-4031aad20af5.png)
![image](https://user-images.githubusercontent.com/87791643/213185882-84a7a47e-656b-4013-9745-ea9ec1de26f0.png)

**Comment by newyorkthink** [comment]
when i run wine, it always caused my system to freezed

**Comment by mmtrt** [comment]
does `winecfg` works

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/213186331-9c6965b0-e6d5-4d48-a5da-9ba153439e5d.png)

**Comment by newyorkthink** [comment]
does winecfg is work ?

**Comment by mmtrt** [comment]
hmm, try wine-devel appimage

**Comment by mmtrt** [comment]
> does winecfg is work ?

it should show winecfg dialog it that worked.

**Comment by newyorkthink** [comment]
ok give me 20min, i download wine-devel

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/213187801-9d53ec78-ee1c-4ae1-a30d-22c9489b5370.png)
winecfg is work

**Comment by mmtrt** [comment]
so wine-staging does not work for you.

**Comment by newyorkthink** [comment]
but i run wine appimage , it caused my system to freeze second.

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/213188517-dd75035a-9860-4418-9e99-009095843819.png)

wine-devel is not work too

**Comment by mmtrt** [comment]
its not appimage issue but app issue with wine

**Comment by mmtrt** [comment]
tho you can install these deps for qq

`./wine-devel_8.0-x86_64.AppImage winetricks -q riched20 fakechinese mfc42`

**Comment by newyorkthink** [comment]
is not about the app , is your build wine appimage cause my syetem freeze and not operate.... :( 
i buzy now, fine.
i use other
