### ISSUE TITLE
cannot execute: "execv error: No such file or directory"

### ISSUE THREAD

**Issue by nerdCopter** [mmtrt/WINE_AppImage#23]
all AppImages report: `execv error: No such file or directory`

`Debian 11 Bullseye`

**Comment by mmtrt** [comment]
Try installing `libc6:i386` if that is not installed.

**Comment by nerdCopter** [comment]
`libc6 is already installed at the requested version (2.31-13+deb11u6)`

**Comment by nerdCopter** [comment]
```
$ sudo dpkg -i libc6-i386_2.31-13+deb11u6_amd64.deb 
(Reading database ... 538522 files and directories currently installed.)
Preparing to unpack libc6-i386_2.31-13+deb11u6_amd64.deb ...
Unpacking libc6-i386 (2.31-13+deb11u6) over (2.31-13+deb11u6) ...
Replaced by files in installed package libc6:i386 (2.31-13+deb11u6) ...
Setting up libc6-i386 (2.31-13+deb11u6) ...
Processing triggers for libc-bin (2.31-13+deb11u6) ...

$ ./wine-staging_ge-proton_8-5-x86_64.AppImage 
execv error: No such file or directory
```

tried `libc6-dev-i386_2.31-13+deb11u6_amd64.deb` as well.

**Comment by mmtrt** [comment]
Alright I will test that in the morning with an older libc system and recent.

**Comment by mmtrt** [comment]
AppImage seems to boot up fine here on both systems Ubuntu 16.04 , Kubuntu 23.10

PS: can you check `apt list --installed 2>/dev/null | grep -e libc6 -e gstreamer -e mesa`

**Comment by nerdCopter** [comment]
<details> 
  <summary>Summary</summary>
  
   

$ apt list --installed 2>/dev/null | grep -e libc6 -e gstreamer -e mesa
gir1.2-gstreamer-1.0/stable,now 1.18.4-2.1 amd64 [installed,automatic]
gstreamer1.0-adapter-pulseeffects/stable,now 4.8.4-1 amd64 [installed]
gstreamer1.0-alsa/stable,now 1.18.4-2 amd64 [installed]
gstreamer1.0-clutter-3.0/stable,now 3.0.27-2 amd64 [installed,automatic]
gstreamer1.0-gl/stable,now 1.18.4-2 amd64 [installed]
gstreamer1.0-gtk3/stable,stable-security,now 1.18.4-2+deb11u1 amd64 [installed]
gstreamer1.0-libav/stable,now 1.18.4-3 amd64 [installed,automatic]
gstreamer1.0-nice/stable,now 0.1.16-1 amd64 [installed]
gstreamer1.0-plugins-bad/stable,now 1.18.4-3 amd64 [installed,automatic]
gstreamer1.0-plugins-base/stable,now 1.18.4-2 amd64 [installed,automatic]
gstreamer1.0-plugins-good/stable,stable-security,now 1.18.4-2+deb11u1 amd64 [installed,automatic]
gstreamer1.0-plugins-ugly/stable,now 1.18.4-2 amd64 [installed,automatic]
gstreamer1.0-pulseaudio/stable,stable-security,now 1.18.4-2+deb11u1 amd64 [installed,automatic]
gstreamer1.0-tools/stable,now 1.18.4-2.1 amd64 [installed]
gstreamer1.0-x/stable,now 1.18.4-2 amd64 [installed,automatic]
libc6-dbg/stable,now 2.31-13+deb11u6 amd64 [installed,automatic]
libc6-dev-i386/stable,now 2.31-13+deb11u6 amd64 [installed,automatic]
libc6-dev-x32/stable,now 2.31-13+deb11u6 amd64 [installed,automatic]
libc6-dev/stable,now 2.31-13+deb11u6 amd64 [installed,automatic]
libc6-i386/stable,now 2.31-13+deb11u6 amd64 [installed,automatic]
libc6-x32/stable,now 2.31-13+deb11u6 amd64 [installed,automatic]
libc6/stable,now 2.31-13+deb11u6 amd64 [installed]
libc6/stable,now 2.31-13+deb11u6 i386 [installed]
libegl-mesa0/stable,now 20.3.5-1 amd64 [installed,automatic]
libegl1-mesa-dev/stable,now 20.3.5-1 amd64 [installed]
libegl1-mesa/stable,now 20.3.5-1 amd64 [installed,automatic]
libgl1-mesa-dev/stable,now 20.3.5-1 amd64 [installed]
libgl1-mesa-dri/stable,now 20.3.5-1 amd64 [installed,automatic]
libgl1-mesa-dri/stable,now 20.3.5-1 i386 [installed]
libgl1-mesa-glx/stable,now 20.3.5-1 amd64 [installed,automatic]
libgl1-mesa-glx/stable,now 20.3.5-1 i386 [installed]
libglapi-mesa/stable,now 20.3.5-1 amd64 [installed,automatic]
libglapi-mesa/stable,now 20.3.5-1 i386 [installed,automatic]
libglu1-mesa-dev/stable,now 9.0.1-1 amd64 [installed]
libglu1-mesa/stable,now 9.0.1-1 amd64 [installed,automatic]
libglx-mesa0/stable,now 20.3.5-1 amd64 [installed,automatic]
libglx-mesa0/stable,now 20.3.5-1 i386 [installed,automatic]
libgstreamer-gl1.0-0/stable,now 1.18.4-2 amd64 [installed,automatic]
libgstreamer-ocaml/stable,now 0.3.0-2+b1 amd64 [installed]
libgstreamer-plugins-bad1.0-0/stable,now 1.18.4-3 amd64 [installed,automatic]
libgstreamer-plugins-base1.0-0/stable,now 1.18.4-2 amd64 [installed,automatic]
libgstreamer-plugins-base1.0-dev/stable,now 1.18.4-2 amd64 [installed]
libgstreamer1.0-0/stable,now 1.18.4-2.1 amd64 [installed,automatic]
libgstreamer1.0-dev/stable,now 1.18.4-2.1 amd64 [installed]
mesa-common-dev/stable,now 20.3.5-1 amd64 [installed,automatic]
mesa-opencl-icd/stable,now 20.3.5-1 amd64 [installed]
mesa-utils-extra/stable,now 8.4.0-1+b1 amd64 [installed]
mesa-utils/stable,now 8.4.0-1+b1 amd64 [installed]
mesa-vdpau-drivers/stable,now 20.3.5-1 amd64 [installed]
mesa-vulkan-drivers/stable,now 20.3.5-1 amd64 [installed,automatic]
mesa-vulkan-drivers/stable,now 20.3.5-1 i386 [installed,automatic]
phonon-backend-gstreamer-common/stable,now 4:4.10.0-1 amd64 [installed,automatic]
phonon4qt5-backend-gstreamer/stable,now 4:4.10.0-1 amd64 [installed]

</details>

**Comment by mmtrt** [comment]
All that looks fine not sure what is causing this issue tbh.

which GPU do you have?

**Comment by nerdCopter** [comment]
Integrated Intel. No discrete GPU.
```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

$ sudo lshw -C video 
  *-display                 
       description: VGA compatible controller
       product: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:31 memory:f7800000-f7bfffff memory:e0000000-efffffff ioport:f000(size=64) memory:c0000-dffff
```

edit: tried on Xubuntu 22.04.2 with NVidia driver 525.105.17 as well with same result.

**Comment by mmtrt** [comment]
I've created wine wow64 experimental appimage builds which uses `wine-32on64-WoW64` means no lib32 needed can you test it.

[wine-devel-wow64](https://github.com/mmtrt/WINE_AppImage/releases/tag/test5-devel)
[wine-staging-wow64](https://github.com/mmtrt/WINE_AppImage/releases/tag/test5-staging)

**Comment by nerdCopter** [comment]
No sir, both fail. staging required `chmod +x`. since original posting, i have seen this error on other (non-wine) projects.  
Debian 12 has releases since as well. Maybe not worth too much effort; unsure. I only wanted an easy option to run a single windows app that is no longer supporting Linux builds.

**Comment by mmtrt** [comment]
can you test again, I've reverted appimages base to jammy.

**Comment by nerdCopter** [comment]
Failed. Tried both assets from actions assets here: https://github.com/mmtrt/WINE_AppImage/actions/runs/5387305090
squashfs image issue here.

```
$ unzip ./wine-devel-exp-wow64-continuous-x86_64.AppImage.zip 
Archive:  ./wine-devel-exp-wow64-continuous-x86_64.AppImage.zip
  inflating: wine-devel-wow64_8.10-x86_64.AppImage.zsync  
  inflating: wine-devel-wow64_8.10-x86_64.AppImage  
$ chmod +x ./wine-devel-wow64_8.10-x86_64.AppImage
$ ./wine-devel-wow64_8.10-x86_64.AppImage 
execv error: No such file or directory
$ ./wine-devel-wow64_8.10-x86_64.AppImage --appimage-extract  
This doesn't look like a squashfs image.
Failed to open squashfs image
```

`Debian GNU/Linux 11 (bullseye)` (XFCE) and `Ubuntu 22.04.2 LTS` (XFCE)

I was able to take this asset: https://github.com/mmtrt/WINE_AppImage/releases/tag/test5-wow64
and execute `./bin/wineconsole`, if such helps in any way
![image](https://github.com/mmtrt/WINE_AppImage/assets/56646290/02e80ad3-c2c8-46c9-a4d2-9141022f9b26)

**Comment by mmtrt** [comment]
AppImages seem to work fine here on Debian 11.7 live

**Comment by nerdCopter** [comment]
interesting, TYVM. sorry for all the loss of time/effort. I will troubleshoot my issues further.

**Comment by thw26** [comment]
I'm seeing this issue as well on a Manjaro machine running the 8.19 devel appimage. @nerdCopter, did you ever find what the issue was?

**Comment by nerdCopter** [comment]
> [...] @nerdCopter, did you ever find what the issue was?

no sir. i gave up.

**Comment by thw26** [comment]
I just found a solution last night. On Manjaro, AppImageLauncher comes preinstalled. Apparently this can cause issues with AppImages. I removed the package and rebooted and the AppImages are working properly again.

**Comment by nerdCopter** [comment]
> I just found a solution last night. On Manjaro, AppImageLauncher comes preinstalled. Apparently this can cause issues with AppImages. I removed the package and rebooted and the AppImages are working properly again.

same solved for me; purged `AppImageLauncher` and it works. thank you!

edit: Other projects suffer from the same: https://github.com/TheAssassin/AppImageLauncher/issues?q=is%3Aissue+%22execv+error%3A+No+such+file+or+directory%22+
