### ISSUE TITLE
0198:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.

### ISSUE THREAD

**Issue by newyorkthink** [mmtrt/WINE_AppImage#26]
![Uploading image.png…]()

**Comment by newyorkthink** [comment]
![image](https://github.com/mmtrt/WINE_AppImage/assets/87791643/11e51c8a-912a-480d-a096-e632c5e2662b)
![image](https://github.com/mmtrt/WINE_AppImage/assets/87791643/9646f6a4-a4d2-41a5-a72d-c46eee4e8128)

**Comment by mmtrt** [comment]
which distro is this, maybe you are missing i386 nvidia drivers?

**Comment by newyorkthink** [comment]
> which distro is this, maybe you are missing i386 nvidia drivers?

debian

**Comment by newyorkthink** [comment]
> which distro is this, maybe you are missing i386 nvidia drivers?

in 2023 year, many people just 64bit not have 32bit

**Comment by mmtrt** [comment]
> 

this needs wow64 build wine to be stable till then i386 drivers are required sadly
