### ISSUE TITLE
feature require: merge Hongkong Chinese fonts and wine-gecko wine-mono

### ISSUE THREAD

**Issue by newyorkthink** [mmtrt/WINE_AppImage#27]
i run wine-stage appimage ,it always need download Gecko
![image](https://github.com/mmtrt/WINE_AppImage/assets/87791643/904c6ee7-1036-4b11-9dbf-e6c9e853f6e1)

feature request

**Comment by mmtrt** [comment]
resolved all these issues also make sure you have `fonts-noto-cjk` installed on system its needed for Chinese support.

**Comment by newyorkthink** [comment]
> resolved all these issues also make sure you have `fonts-noto-cjk` installed on system its needed for Chinese support.

thanks
