### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by liberodark** [mmtrt/WINE_AppImage#3]
Hi,

Is very strange im not sure how to use it.

Exemple : 

`./wine-stable-x86_64.AppImage Pokemon\ Uranium/game_info/data/Uranium.exe `

Not run the game only have error : 

```
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
wine: configuration in L"/home/pc/.wine" has been updated.
0009:err:module:__wine_process_init L"C:\\windows\\system32\\Pokemon.exe" not found
```

You have any idea for what is not supporting space ?

Have make this test  too (no space) : 

That work.
`./wine-stable-x86_64.AppImage ./Uranium.exe`

But wine is support this : 

That work.
`wine Pokemon\ Uranium/game_info/data/Uranium.exe`

**Comment by mmtrt** [comment]
~~Its known issue I should have mentioned in read me anyways [see](https://github.com/AppImageCrafters/AppRun/issues/16) OR create [issue](https://github.com/AppImageCrafters/AppRun/issues/) in `AppRun` repo which this app-image uses.~~

**Comment by mmtrt** [comment]
@liberodark use two backslashes instead of one should work.

`./wine-stable-x86_64.AppImage Pokemon\\ Uranium/game_info/data/Uranium.exe `
