### ISSUE TITLE
Features request: merge Korean Fonts in Wine_AppImage

### ISSUE THREAD

**Issue by newyorkthink** [mmtrt/WINE_AppImage#35]
some font is not show, 
![image](https://github.com/mmtrt/WINE_AppImage/assets/87791643/3162dece-5fd0-41df-9002-54258c6f123f)

or you can Make local system font in AppRun
```
--bind=/home --bind=/home/$(echo $USER) --bind=/media --bind=/mnt --bind=/opt --bind=/usr/lib/locale --bind=/etc/fonts --bind=/usr/share/fonts --bind=/usr/share/fontconfig
```

**Comment by mmtrt** [comment]
use winetricks to install it.

`./wine-staging_8.13-x86_64.AppImage winetricks fakekorean`
