### ISSUE TITLE
i test some software , i find the bug, but i cannot said what happen with wine_APPimage

### ISSUE THREAD

**Issue by newyorkthink** [mmtrt/WINE_AppImage#38]
hi,
first, I test CS 1.6 game, when I open CS1.6, it can go into the CS1.6 platform, but, I select map to play it.
it always loading map, they so it cannot into the map in wine_APPimage

second, I test left 4 game ,it have same situation in wine_APPIMAG

third, i play video by jriver and the screen just show black , finaly the jriver is auto close.

so, I find some bug, but I don't what it happen

**Comment by mmtrt** [comment]
just tested left 4 dead working fine here, if you have nvidia gpu make sure you have i386 nvidia driver packages installed otherwise games will not boot.

**Comment by newyorkthink** [comment]
> 

I found online, I not found í386 nvidia driver. 
how can you install i386 nvidia driver?

is debian os?

**Comment by mmtrt** [comment]
`sudo apt install nvidia-driver-libs:i386`
