### ISSUE TITLE
How to build identically a stable version of wine appimage?

### ISSUE THREAD

**Issue by bozothegeek** [mmtrt/WINE_AppImage#46]
Hi @mmtrt ,
First, thanks for all your job already done on the Wine Appimage, congratulations !
From my side, I'm searching to learn more on generation of appimage for wine, it's very usefull finally to test different versions/implementations. Good idea !
Thanks also about the update of instruction to build "manually" without runner that you did begin of August.
I followed all instructions (I did also several times)
The installation of Wine is working well
But unfortunately the behavior is different :-(
I have some windows in "black" without crash :-(
I tried several times, I tested several images and I decided to stay on 8.0.2 because that stable and you generated by pipeline one week ago. For sure I used the tagged commit "continious-stable"
To understand, I extract the files from appimage and I compared and I discovered that we don't have the same content that could explain certainly the difference of behavior.
With tool like beyond compare, we could see for example for "systemd":
![image](https://github.com/mmtrt/WINE_AppImage/assets/46259969/e6fb0deb-1b65-4f03-8862-20ae556ee596)
What do you think ? is it normal ? did I do a mistake ? is it do to content of package that they changed ?
Thanks in advance for your reply
Best regards,

**Comment by mmtrt** [comment]
compare `.bundle.yml` file on both AppImages for added packages difference, though systemd inclusion shouldn't make difference tbh.

**Comment by bozothegeek** [comment]
@mmtrt Thanks, OK, I will try that to understand what is different... I already tried previously but it's not the same sorting in both file... I need to find a powerfull tool certainly ;-)

**Comment by bozothegeek** [comment]
@mmtrt It's OK, I reorder the line to be able to compare... Please see the difference ;-)
![image](https://github.com/mmtrt/WINE_AppImage/assets/46259969/f99a9eeb-1647-4a04-afd2-2251ae487123)
I will try to add these packages now... to hope to have the same behavior at the end !
