### ISSUE TITLE
feature request: merge nvidia library in APPimage

### ISSUE THREAD

**Issue by newyorkthink** [mmtrt/WINE_AppImage#47]
I found the yaml file its not 
![image](https://github.com/mmtrt/WINE_AppImage/assets/87791643/701c6e11-6ff5-4ac0-9375-ed4ea2050825)

**Comment by kenderipa** [comment]
I second that. Since I'm using nVidia propriatary drivers, it makes your AppImages useless for me.

**Comment by kenderipa** [comment]
Any feedback? Current builds remain unusable for games.
