### ISSUE TITLE
Getting libcurl.so.4 "no version information available" and execv error, cannot run

### ISSUE THREAD

**Issue by ADHDefy** [mmtrt/WINE_AppImage#49]
Here's what my terminal says when I try to execute the GE-Proton AppImage:

```
$ ./wine-staging_ge-proton_8-24-x86_64.AppImage

/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
execv error: No such file or directory
```

I googled around, I can't seem to figure out what would cause this. I'm on Fedora 39 KDE.

**Comment by mmtrt** [comment]
check #23 seems similar issue.

**Comment by ADHDefy** [comment]
It sure is! Looks like AppImageLauncher was the problem.  Thank you!
