### ISSUE TITLE
Graphic accelaration will not work on Nvidia systems

### ISSUE THREAD

**Issue by azubieta** [mmtrt/WINE_AppImage#5]
Then Nvidia kernel  extension requires a client library of the same version, therefore if an AppImage embeds such library it will not work.

The solution for this is not including the graphic stack libraries in the bundle, for a list of which package should be omitted please check: https://github.com/AppImageCrafters/appimage-builder/blob/180dc6fb0a946da2f8606b070afc1ccd0b493bf7/AppImageBuilder/app_dir/bundlers/apt/package_lists.py#L64

**Comment by mmtrt** [comment]
This should do it https://github.com/mmtrt/WINE_AppImage/commit/35f6e84edbcb43e7b27bc4ad27bfa1bce905c0e6

**Comment by azubieta** [comment]
Indeed, but you could also not add those packages to the `AppDir > apt > incude ` section.
