### ISSUE TITLE
cannot run it  tmp/.mount_wine-sMiLpeO/wrapper: line 95: /tmp/.mount_wine-sMiLpeO/usr/bin/wine: No such file or directory

### ISSUE THREAD

**Issue by newyorkthink** [mmtrt/WINE_AppImage#52]
![image](https://github.com/mmtrt/WINE_AppImage/assets/87791643/e9757799-a85e-45b0-876b-c5ce31f7b3d1)

**Comment by newyorkthink** [comment]
![image](https://github.com/mmtrt/WINE_AppImage/assets/87791643/ec05abd6-1f66-41b7-bafa-a1a3a8fddadb)

**Comment by mmtrt** [comment]
sadly appimage runtime v3 does not work if host does not have `libc6:i386` installed that though you can use `wow64` builds.
