### ISSUE TITLE
Is there going to be a WOW64 Appimage of Wine stable 9.0?

### ISSUE THREAD

**Issue by user1-github** [mmtrt/WINE_AppImage#53]
I would personally like to have a Wine stable Appimage that is as small as possible, which contains only Wine itself and its required dependencies (only those which are absolutely required by Wine) without all the additional bloat like Mesa drivers. Now that WOW64 mode is complete in Wine stable 9.0, I think it should be possible to create such Appimage.

**Comment by mmtrt** [comment]
here test build of wine-stable 9 with wow64 enabled https://github.com/mmtrt/WINE_AppImage/releases/tag/test6

**Comment by user1-github** [comment]
Great, thanks!
I'll have a chance to test it later, so I guess this can be closed.
I'll open a new issue if there will be problems.
