### ISSUE TITLE
Unable to execute wine-staging_ge-proton_8-25 in SteamOS

### ISSUE THREAD

**Issue by mvgian** [mmtrt/WINE_AppImage#57]
I'm getting below errors when executing the latest wine-staging_ge-proton_8-25 in Steam Deck desktop mode

(126)(deck@steamdeck Proton)$ ./wine-staging_ge-proton_8-25-x86_64.AppImage
/tmp/.mount_wine-sAlIciD/wrapper: line 24: syntax error near unexpected token `done'
/tmp/.mount_wine-sAlIciD/wrapper: line 24: ` done'

**Comment by mmtrt** [comment]
should be fixed now update or redownload appimage.
