### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by b-antwan** [mmtrt/WINE_AppImage#60]
Hello!
I've been trying to run the new stable AppImage (wine 9.0) on ubuntu 16 and noticed it didn't work so decided to stop testing on there and switch to the oldest still supported version of ubuntu (20.04 I believe) and I can't run it because of glibc errors:

 ```
 /tmp/.mount_wine.AaAeJoA/bin/bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_wine.AaAeJoA/bin/bash)
/tmp/.mount_wine.AaAeJoA/bin/bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_wine.AaAeJoA/bin/bash)
/tmp/.mount_wine.AaAeJoA/bin/bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_wine.AaAeJoA/lib/x86_64-linux-gnu/libtinfo.so.6)
 ```
 
 Same thing happens when I try running it with `--appimage-extract-and-run` or `--appimage-extract` and then running the AppRun manually. 
 
 Is this expected?

**Comment by mmtrt** [comment]
Try this [build](https://github.com/mmtrt/WINE_AppImage/releases/download/test6/wine-stable_9.0-x86_64.AppImage) see if this works.

**Comment by b-antwan** [comment]
@mmtrt the build works on ubuntu 20.04!

**Comment by mmtrt** [comment]
now try from releases

**Comment by b-antwan** [comment]
Wine starts and works. Thanks a lot!
I am having USB issues, but I don't have much more information than that for now.
Thanks!

**Comment by mmtrt** [comment]
closing this since actual issue was fixed
