### ISSUE TITLE
wine-staging_ge-proton_8-26-x86_64.AppImage - /usr/bin/wine file not found

### ISSUE THREAD

**Issue by nadrolinux** [mmtrt/WINE_AppImage#63]
Hello,
The latest version of ProtonGE 8-26 doesn't work for me. When I try to run Proton GE via AppImage directly or AppRun I just see '/usr/bin/wine: file not found' error. I don't see this issue with the latest Wine AppImage builds.
Patryk

**Comment by marco-calautti** [comment]
I am also experiencing the same issue

**Comment by mmtrt** [comment]
it should be working now.
