### ISSUE TITLE
Wayland support in 9.22

### ISSUE THREAD

**Issue by nadrolinux** [mmtrt/WINE_AppImage#65]
Hello,

When I tried to set graphics to wayland:
```
Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\Software\Wine\Drivers]
"Graphics"="wayland"
```
I see a following error:
`013c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.`

In wine 9.22 wayland should be available oob, so it looks like a problem with AppImage build (maybe some build settings or libwayland-client missing idk)

I'm testing wine-staging on Fedora Silverblue 41.

**Comment by mmtrt** [comment]
it is working now after adding the registry.

![Screenshot_20241212_215929](https://github.com/user-attachments/assets/1ca92e55-5627-4803-8738-0f8fd01df85e)
