### ISSUE TITLE
How to Install GPU Packages

### ISSUE THREAD

**Issue by Amarjit3** [mmtrt/WINE_AppImage#8]
Hello,

You have mentioned in the README to install the GPU drivers before installing the AppImage. How does one do that? I am using Ubuntu 20.04.

Many thanks and kind regards.

**Comment by mmtrt** [comment]
Should be these packages stated by,
https://github.com/AppImageCrafters/appimage-builder/blob/5732219cef0985961b477727aca7446a27fa0289/appimagebuilder/modules/deploy/apt/listings.py#L62

**Comment by tts-035** [comment]
You need a package what contain libGL.so.1 + dri libs, both 32 bit and 64 bit versions
It should also install other required depences

### On ubuntu/debian:
```
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install libgl1 libgl1:i386 libgl1-mesa-dri libgl1-mesa-dri:i386
```

### On opensuse:
`sudo zypper install libglvnd libglvnd-32bit Mesa-dri Mesa-dri-32bit`


### On fedora/centos:
`sudo yum install libglvnd libglvnd.i686 mesa-dri-drivers mesa-dri-drivers.i686`

**Comment by tts-035** [comment]
If you need vulkan do also:

On ubuntu/debian:
`sudo apt install libvulkan1 libvulkan1:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386`

On opensuse:

```
sudo zypper install libvulkan1 libvulkan1-32bit Mesa-vulkan-overlay Mesa-vulkan-overlay-32bit
###you can choose only inel or radeon or install both
sudo zypper install libvulkan_intel libvulkan_intel-32bit libvulkan_radeon libvulkan_radeon-32bit
```


On fedora/centos:
`sudo yum install vulkan-loader vulkan-loader.i686 mesa-vulkan-drivers mesa-vulkan-drivers.i686`

**Comment by matheuswillder** [comment]
> You need a package what contain libGL.so.1 + dri libs, both 32 bit and 64 bit versions It should also install other required depences
> ### On ubuntu/debian:
> 
> ```
> sudo dpkg --add-architecture i386
> sudo apt update
> sudo apt install libgl1 libgl1:i386 libgl1-mesa-dri libgl1-mesa-dri:i386
> ```

Thanks for the tip, very useful!

> Should be these packages stated by, https://github.com/AppImageCrafters/appimage-builder/blob/5732219cef0985961b477727aca7446a27fa0289/appimagebuilder/modules/deploy/apt/listings.py#L62

@mmtrt Is there any technical reason to not include these packages? Just curiosity, because this would make much easier to use these compilations to gaming, for example, as Wine usually has regressions in some games from time to time and there is no way to (easily) rollback an version installed from a repository.

Thank you for maintening these compilations.

**Comment by mmtrt** [comment]
AppImage now includes i386 drivers and works without host i386 packages.

**Comment by ghost** [comment]
@mmtrt Sorry for necroposting but now that Wine11 arrives with full WOW64 support, can I simply run 32-bit .exe without enabling i386?

**Comment by matheuswillder** [comment]
You can, WoW64 has worked without problems in all the programs I tested without requiring any additional installation, but apparently games that depend on the GPU are no longer working with this AppImage build as they used to.

I'm no longer following this project closely, so I don't know in which builds this started.
