### ISSUE TITLE
Document printing does not work

### ISSUE THREAD

**Issue by tts-035** [mmtrt/WINE_AppImage#9]
Printing documents inside wine does not work because cups is not included in this AppImage. Windows applications cannot detect the printer.

**Comment by tts-035** [comment]
I extracted this AppImage, copied cups-bsd and cups-client binaries + libcups-amd64 and libcups2-i386 and now everything works.

I think it would be good to include these in future releases if possible because it takes only 2.5-5 megabytes (without compression).

**Comment by mmtrt** [comment]
Shouldn't these pkgs come pre install in some distributions if not user can install them.

Also users that do print stuff have them install already.

**Comment by tts-035** [comment]
I realized that printing does not work when I use a 32-bit prefix or 32-bit applications. Apparently it's because I don't have 32-bit libraries or something
Everything works only after these modifications are made

**Comment by mmtrt** [comment]
Hi, sorry for being late, I've added cups libs so can you test again for printing that would be great.

**Comment by mmtrt** [comment]
no response closing.

**Comment by tts-035** [comment]
Hello! I'm sorry for my late reply. My printer is broken, so I won't be able to test this feature right now. I will try to test the print function later
